import React, { useState } from "react";
import { useChat } from "../hooks/useChat";

interface PairModalProps {
  isOpen: boolean;
  onClose: () => void;
}

const PairModal: React.FC<PairModalProps> = ({ isOpen, onClose }) => {
  const { pairLocalDevice, isPairing } = useChat();
  const [pairingCode, setPairingCode] = useState("");
  const [statusMsg, setStatusMsg] = useState<{
    type: "success" | "error" | "info";
    text: string;
  } | null>(null);

  if (!isOpen) return null;

  const handlePair = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!pairingCode.trim()) return;

    setStatusMsg({ type: "info", text: "Pairing with local desktop device..." });
    try {
      const res = await pairLocalDevice(pairingCode.trim());
      if (res.success) {
        setStatusMsg({
          type: "success",
          text: `🎉 Device successfully paired! Device ID: ${
            res.data?.deviceId || "Connected"
          }`,
        });
        setPairingCode("");
      } else {
        setStatusMsg({
          type: "error",
          text: res.message || "Pairing failed. Check the code and try again.",
        });
      }
    } catch (err: any) {
      setStatusMsg({
        type: "error",
        text: err.message || "Failed to pair device. Ensure backend is running.",
      });
    }
  };

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div
        className="modal-content"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="modal-header">
          <div className="modal-title">
            <span className="modal-icon">🔗</span>
            <h3>Pair Local Desktop (Local-BE)</h3>
          </div>
          <button className="close-btn" onClick={onClose}>
            ✕
          </button>
        </div>

        <p className="modal-desc">
          Enter the 6-character Pairing Code generated by your local desktop
          agent (e.g. <code>NX-SQF2</code> from <code>Local-BE/dist/nexus.exe</code>)
          to link desktop command execution with your Nexus account.
        </p>

        <form onSubmit={handlePair} className="modal-form">
          <div className="input-group">
            <label>Pairing Code</label>
            <input
              type="text"
              placeholder="e.g. NX-SQF2"
              value={pairingCode}
              onChange={(e) => setPairingCode(e.target.value.toUpperCase())}
              maxLength={10}
              className="code-input"
              autoFocus
            />
          </div>

          {statusMsg && (
            <div className={`modal-status ${statusMsg.type}`}>
              {statusMsg.text}
            </div>
          )}

          <div className="modal-actions">
            <button
              type="button"
              className="btn btn-secondary"
              onClick={onClose}
            >
              Cancel
            </button>
            <button
              type="submit"
              className="btn btn-primary"
              disabled={isPairing || !pairingCode.trim()}
            >
              {isPairing ? "Pairing..." : "Connect Device"}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default PairModal;
